### ISSUE TITLE
Do you write wrong materials' id?

### ISSUE THREAD

**Issue by LorZangel** [Auxilor/EcoEnchants#15]
[13:13:19] [Server thread/ERROR]: Error occurred while enabling EcoEnchants v5.1.1 (Is it up to date?)
java.lang.NoSuchFieldError: NETHERITE_HELMET
    at com.willfp.ecoenchants.enchantments.ecoenchants.normal.Plasmic.<clinit>(Plasmic.java:22) ~[?:?]
    at com.willfp.ecoenchants.enchantments.EcoEnchants.<clinit>(EcoEnchants.java:254) ~[?:?]
    at com.willfp.ecoenchants.loader.Loader.load(Loader.java:213) ~[?:?]
    at com.willfp.ecoenchants.EcoEnchantsPlugin.onEnable(EcoEnchantsPlugin.java:38) ~[?:?]
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.15.2.jar:git-Paper-387]
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.15.2.jar:git-Paper-387]
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.15.2.jar:git-Paper-387]
    at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:472) ~[patched_1.15.2.jar:git-Paper-387]
    at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:386) ~[patched_1.15.2.jar:git-Paper-387]
    at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:235) ~[patched_1.15.2.jar:git-Paper-387]
    at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:909) ~[patched_1.15.2.jar:git-Paper-387]
    at java.lang.Thread.run(Thread.java:748) [?:1.8.0_275]
java.lang.NoSuchFieldError: NETHERITE_HELMET
    at

**Comment by lokka30** [comment]
you are running a 1.15 server, netherite helmet only exists in 1.16+ :)
