### ISSUE TITLE
dependencies? 

### ISSUE THREAD

**Issue by Trinchezito** [Auxilor/EcoEnchants#153]
I already have latest protocollib and the server is on 1.18. 
```
[04:32:56] [Server thread/ERROR]: Could not load 'plugins/EcoEnchants v8.39.2.jar' in folder 'plugins'
org.bukkit.plugin.UnknownDependencyException: Unknown/missing dependency plugins: [eco]. Please download and install these plugins to run 'EcoEnchants'.
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:290) ~[purpur-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_18_R1.CraftServer.loadPlugins(CraftServer.java:422) ~[purpur-1.18.1.jar:git-Purpur-1551]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:320) ~[purpur-1.18.1.jar:git-Purpur-1551]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1218) ~[purpur-1.18.1.jar:git-Purpur-1551]
	at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:322) ~[purpur-1.18.1.jar:git-Purpur-1551]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by Fantom250YT** [comment]
Install Eco
https://github.com/Auxilor/eco/releases

**Comment by Fantom250YT** [comment]
@Trinchezito Issue fixed?
