### ISSUE TITLE
Bug when entity dies from another entity.

### ISSUE THREAD

**Issue by WobbyChip** [Auxilor/EcoEnchants#183]
Server Information (please complete the following information):

Version: (output of /ver command)
This server is running CraftBukkit version 3452-Spigot-ffceeae-808cb7c (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT)

Version of plugin and eco (/ver eco, /ver )
[14:46:09 INFO]: eco version 6.27.2
[14:46:11 INFO]: EcoEnchants version 8.44.0

Caused by: java.lang.NoSuchMethodError: 'boolean org.bukkit.event.entity.EntityDeathEvent.isCancelled()'
        at com.willfp.ecoenchants.libreforge.triggers.triggers.TriggerEntityItemDrop.handle(TriggerEntityItemDrop.kt:28) ~[?:?]

[14:04:15] [Server thread/ERROR]: Could not pass event EntityDeathByEntityEvent to EcoEnchants v8.44.0
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[spigot-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[spigot-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at com.willfp.eco.internal.spigot.eventlisteners.EntityDeathByEntityBuilder.push(EntityDeathByEntityBuilder.kt:28) ~[?:?]
        at com.willfp.eco.internal.spigot.eventlisteners.EntityDeathByEntityListeners.onEntityDeath(EntityDeathByEntityListeners.kt:62) ~[?:?]
        at jdk.internal.reflect.GeneratedMethodAccessor269.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[spigot-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[spigot-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:819) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3452-Spigot-ffceeae-808cb7c]
        at net.minecraft.world.entity.EntityLiving.f(EntityLiving.java:1660) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3452-Spigot-ffceeae-808cb7c]
        at net.minecraft.world.entity.EntityLiving.a(EntityLiving.java:1600) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3452-Spigot-ffceeae-808cb7c]
        at net.minecraft.world.entity.EntityLiving.a(EntityLiving.java:1431) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3452-Spigot-ffceeae-808cb7c]
        at net.minecraft.world.entity.monster.EntityZombie.a(EntityZombie.java:300) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3452-Spigot-ffceeae-808cb7c]
        at net.minecraft.world.entity.projectile.EntityArrow.a(EntityArrow.java:387) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3452-Spigot-ffceeae-808cb7c]
        at net.minecraft.world.entity.projectile.IProjectile.a(IProjectile.java:169) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3452-Spigot-ffceeae-808cb7c]
        at net.minecraft.world.entity.projectile.IProjectile.preOnHit(IProjectile.java:160) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3452-Spigot-ffceeae-808cb7c]
        at net.minecraft.world.entity.projectile.EntityArrow.k(EntityArrow.java:231) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3452-Spigot-ffceeae-808cb7c]
        at net.minecraft.world.entity.projectile.EntityTippedArrow.k(EntityTippedArrow.java:112) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3452-Spigot-ffceeae-808cb7c]
        at net.minecraft.server.level.WorldServer.a(WorldServer.java:804) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3452-Spigot-ffceeae-808cb7c]
        at net.minecraft.world.level.World.a(World.java:700) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3452-Spigot-ffceeae-808cb7c]
        at net.minecraft.server.level.WorldServer.lambda$9(WorldServer.java:401) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3452-Spigot-ffceeae-808cb7c]
        at net.minecraft.world.level.entity.EntityTickList.a(SourceFile:54) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3452-Spigot-ffceeae-808cb7c]
        at net.minecraft.server.level.WorldServer.a(WorldServer.java:381) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3452-Spigot-ffceeae-808cb7c]
        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1330) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3452-Spigot-ffceeae-808cb7c]
        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:429) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3452-Spigot-ffceeae-808cb7c]
        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1237) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3452-Spigot-ffceeae-808cb7c]
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1047) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3452-Spigot-ffceeae-808cb7c]
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:304) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3452-Spigot-ffceeae-808cb7c]
        at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.NoSuchMethodError: 'boolean org.bukkit.event.entity.EntityDeathEvent.isCancelled()'
        at com.willfp.ecoenchants.libreforge.triggers.triggers.TriggerEntityItemDrop.handle(TriggerEntityItemDrop.kt:28) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-api-1.18.2-R0.1-SNAPSHOT.jar:?]

**Comment by WobbyChip** [comment]
Server Information (please complete the following information):

Version: (output of /ver command)
This server is running CraftBukkit version 3452-Spigot-ffceeae-808cb7c (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT)

Version of plugin and eco (/ver eco, /ver <plugin>)
[14:46:09 INFO]: eco version 6.27.2
[14:46:11 INFO]: EcoEnchants version 8.44.0
