### ISSUE TITLE
Unable to load plugin

### ISSUE THREAD

**Issue by blu-jay** [Auxilor/EcoEnchants#196]
Hi, I'm getting this error when im trying to do a fresh install of the plugin.

**Java:** openjdk version "17.0.1" 2021-10-19 LTS
**Server:** Paper version git-Paper-268 (MC: 1.18.2) (Latest)
**EcoEnchants:** v8.51.1
**Eco:** 6.31.0

`Could not load 'plugins/EcoEnchants v8.51.0.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.NoSuchMethodError: 'void kotlin.jvm.internal.FunctionReferenceImpl.<init>(int, java.lang.Object, java.lang.Class, java.lang.String, java.lang.String, int)'
    at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:157) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
    at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:415) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
    at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:323) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
    at org.bukkit.craftbukkit.v1_18_R2.CraftServer.loadPlugins(CraftServer.java:417) ~[paper-1.18.2.jar:git-Paper-268]
    at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:288) ~[paper-1.18.2.jar:git-Paper-268]
    at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1163) ~[paper-1.18.2.jar:git-Paper-268]
    at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.18.2.jar:git-Paper-268]
    at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NoSuchMethodError: 'void kotlin.jvm.internal.FunctionReferenceImpl.<init>(int, java.lang.Object, java.lang.Class, java.lang.String, java.lang.String, int)'
    at com.willfp.ecoenchants.libreforge.LibReforgePlugin$registerJavaHolderProvider$1.<init>(LibReforge.kt) ~[EcoEnchants v8.51.0.jar:?]
    at com.willfp.ecoenchants.libreforge.LibReforgePlugin.registerJavaHolderProvider(LibReforge.kt:87) ~[EcoEnchants v8.51.0.jar:?]
    at com.willfp.ecoenchants.EcoEnchantsPlugin.<init>(EcoEnchantsPlugin.java:85) ~[EcoEnchants v8.51.0.jar:?]
    at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
    at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?]
    at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
    at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
    at java.lang.reflect.ReflectAccess.newInstance(ReflectAccess.java:128) ~[?:?]
    at jdk.internal.reflect.ReflectionFactory.newInstance(ReflectionFactory.java:347) ~[?:?]
    at java.lang.Class.newInstance(Class.java:645) ~[?:?]
    at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:83) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
    at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:153) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
    ... 7 more`

**Comment by blu-jay** [comment]
Also talked about this in the discord https://discord.com/channels/452518336627081236/748978249740058704/957713633218035772

**Comment by Awindai** [comment]
Can I 1up this post? Would very much like to see a fix to that..

**Comment by blu-jay** [comment]
Found the issue. Turns out that EcoEnchants is trying to load classes from other plugins that have older versions of kotlin.

The issue was caused by 2 a very out of date plugins (which I think were shading an older version of kotlin)
I believe there should be a way to prevent loading classes from other plugins like this, though I can't think of it off the top of my head. 

The two plugins in question (they still work despite their age): 
-> [AutoRestartV4](https://www.spigotmc.org/resources/autorestart.2538/)
-> [CommandAlias](https://www.spigotmc.org/resources/commandalias.44362/)

**Comment by NewJeb** [comment]
I love eco support, I wrote 0 support on the discord, although it was calculated for this purpose, after several days of ignoring, I went to write an angry review. The answer was not long in coming, we are not bad, we will fix everything blah blah, write to our github. And who answers me? A normal admin who has the same problem, thank you very much, I really have an alias plugin. It's their job, not ours. If it can't be fixed in any way, I will delete it, by the way, this has never happened before.

**Comment by blu-jay** [comment]
> 

sorry I don't understand?
I'm not an admin or a maintainer of the plugin, I just made a similar bug report and wanted to link our issues together.

**Comment by Scottlander100** [comment]
I'm receiving this issue too after updating to the newest version of paper. Getting the error for all eco plugins I have. I don't have either of the two plugins mentioned above installed. Looking forward to an update when it's available. Error message listed below

[02:07:37 ERROR]: Could not load 'plugins/EcoCrates v1.9.2.jar' in folder 'plugins'
org.bukkit.plugin.UnknownDependencyException: Unknown/missing dependency plugins: [ProtocolLib]. Please download and install these plugins to run 'EcoCrates'.
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:291) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.loadPlugins(CraftServer.java:418) ~[paper-1.18.2.jar:git-Paper-323]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:288) ~[paper-1.18.2.jar:git-Paper-323]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1163) ~[paper-1.18.2.jar:git-Paper-323]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.18.2.jar:git-Paper-323]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[02:07:37 ERROR]: Could not load 'plugins/EcoEnchants v8.62.0.jar' in folder 'plugins'
org.bukkit.plugin.UnknownDependencyException: Unknown/missing dependency plugins: [ProtocolLib]. Please download and install these plugins to run 'EcoEnchants'.
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:291) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.loadPlugins(CraftServer.java:418) ~[paper-1.18.2.jar:git-Paper-323]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:288) ~[paper-1.18.2.jar:git-Paper-323]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1163) ~[paper-1.18.2.jar:git-Paper-323]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.18.2.jar:git-Paper-323]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[02:07:37 ERROR]: Could not load 'plugins/eco-6.35.4-all.jar' in folder 'plugins'
org.bukkit.plugin.UnknownDependencyException: Unknown/missing dependency plugins: [ProtocolLib]. Please download and install these plugins to run 'eco'.
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:291) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.loadPlugins(CraftServer.java:418) ~[paper-1.18.2.jar:git-Paper-323]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:288) ~[paper-1.18.2.jar:git-Paper-323]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1163) ~[paper-1.18.2.jar:git-Paper-323]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.18.2.jar:git-Paper-323]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
