### ISSUE TITLE
Bug from startup

### ISSUE THREAD

**Issue by NewJeb** [Auxilor/EcoEnchants#204]
**Expected behavior**
I try to run it but it just won't run! At the same time, I even tried deleting the folder for regenerating configs

**Server Information (please complete the following information):**
- Version: Previous version: git-Matter-49 (MC: 1.18.2)
- Version of plugin and eco: ecoenchants - 8.57.5, eco - 6.34.0 

**Additional context**
[20:58:09] [Server thread/WARN]: [eco] Loaded class org.slf4j.impl.StaticLoggerBinder from BoardGames v1.0.16 which is not a depend or softdepend of this plugin.
[20:58:13] [Server thread/INFO]: [com.willfp.eco.libs.reflections.Reflections] Reflections took 3475 ms to scan 81 urls, producing 124 keys and 50003 values 
[20:58:13] [Server thread/WARN]: [EcoEnchants] Loaded class kotlin.jvm.internal.Intrinsics from CommandAlias v1.6.6-RELEASE which is not a depend or softdepend of this plugin.
[20:58:15] [Server thread/INFO]: [com.willfp.eco.libs.reflections.Reflections] Reflections took 2290 ms to scan 81 urls, producing 85 keys and 35806 values 
[20:58:15] [Server thread/WARN]: [eco] Loaded class net.md_5.bungee.api.event.ServerConnectedEvent from NashornPlus v1.1.0 which is not a depend or softdepend of this plugin.
[20:58:15] [Server thread/ERROR]: Could not load 'plugins/EcoEnchants v8.57.5.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.NoSuchMethodError: 'void kotlin.jvm.internal.FunctionReferenceImpl.<init>(int, java.lang.Object, java.lang.Class, java.lang.String, java.lang.String, int)'
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:157) ~[pufferfish-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:415) ~[pufferfish-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:323) ~[pufferfish-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.loadPlugins(CraftServer.java:417) ~[pufferfish-1.18.2.jar:git-Pufferfish-60]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:290) ~[pufferfish-1.18.2.jar:git-Pufferfish-60]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1165) ~[pufferfish-1.18.2.jar:git-Pufferfish-60]
	at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:317) ~[pufferfish-1.18.2.jar:git-Pufferfish-60]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NoSuchMethodError: 'void kotlin.jvm.internal.FunctionReferenceImpl.<init>(int, java.lang.Object, java.lang.Class, java.lang.String, java.lang.String, int)'
	at com.willfp.ecoenchants.libreforge.LibReforgePlugin$registerJavaHolderProvider$1.<init>(LibReforge.kt) ~[EcoEnchants v8.57.5.jar:?]
	at com.willfp.ecoenchants.libreforge.LibReforgePlugin.registerJavaHolderProvider(LibReforge.kt:88) ~[EcoEnchants v8.57.5.jar:?]
	at com.willfp.ecoenchants.EcoEnchantsPlugin.<init>(EcoEnchantsPlugin.java:85) ~[EcoEnchants v8.57.5.jar:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
	at java.lang.reflect.ReflectAccess.newInstance(ReflectAccess.java:128) ~[?:?]
	at jdk.internal.reflect.ReflectionFactory.newInstance(ReflectionFactory.java:347) ~[?:?]
	at java.lang.Class.newInstance(Class.java:645) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:85) ~[pufferfish-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:153) ~[pufferfish-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	... 7 more

**Comment by blu-jay** [comment]
Hey, I believe your issue is related to mine. Probably a plugin conflict and some issue with the dependency loader.

[Link to the issue](https://github.com/Auxilor/EcoEnchants/issues/196 )

**Comment by WillFP** [comment]
CommandAlias needs to relocate kotlin
