### ISSUE TITLE
Console spam and enchants not working

### ISSUE THREAD

**Issue by good3n** [Auxilor/EcoEnchants#207]
```
[09:18:24 ERROR]: Could not pass event BlockBreakEvent to EcoEnchants v8.59.2
java.lang.StackOverflowError: null
        at org.bukkit.block.BlockFace.values(BlockFace.java:9) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
```

Lumberjack
Using eco 6.35.1
Paper 301

About a billion lines of this afterwards...
```
at com.willfp.eco.util.BlockUtils.getNearbyBlocks(BlockUtils.java:45) ~[eco-6.35.1-all (1).jar:?]
        at com.willfp.eco.util.BlockUtils.getNearbyBlocks(BlockUtils.java:45) ~[eco-6.35.1-all (1).jar:?]
        at com.willfp.eco.util.BlockUtils.getNearbyBlocks(BlockUtils.java:45) ~[eco-6.35.1-all (1).jar:?]
        at com.willfp.eco.util.BlockUtils.getNearbyBlocks(BlockUtils.java:45) ~[eco-6.35.1-all (1).jar:?]
        at com.willfp.eco.util.BlockUtils.getNearbyBlocks(BlockUtils.java:45) ~[eco-6.35.1-all (1).jar:?]
        at com.willfp.eco.util.BlockUtils.getNearbyBlocks(BlockUtils.java:45) ~[eco-6.35.1-all (1).jar:?]
        at com.willfp.eco.util.BlockUtils.getNearbyBlocks(BlockUtils.java:45) ~[eco-6.35.1-all (1).jar:?]
```

**Comment by WillFP** [comment]
Fixed in latest eco
