### ISSUE TITLE
java.lang.NoClassDefFoundError: org/bukkit/entity/Allay

### ISSUE THREAD

**Issue by Dungjava** [Auxilor/EcoEnchants#261]
[07:16:36 ERROR]: Could not pass event EntityDamageByEntityEvent to EcoSkills v1.55.2
java.lang.NoClassDefFoundError: org/bukkit/entity/Allay
        at com.willfp.ecoskills.stats.DamageIndicatorListener.onEntityDamageByEntity(DamageIndicatorListener.kt:43) ~[EcoSkills v1.55.2.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor165.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[pearl-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[pearl-api-1.18.2-R0.1-SNAPSHOT.jar:git-Pearl-"cf05459"]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[pearl-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:734) ~[pearl-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.event.CraftEventFactory.callEvent(CraftEventFactory.java:248) ~[pearl-1.18.2.jar:git-Pearl-"cf05459"]
        at org.bukkit.craftbukkit.v1_18_R2.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:1149) ~[pearl-1.18.2.jar:git-Pearl-"cf05459"]
        at org.bukkit.craftbukkit.v1_18_R2.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:1008) ~[pearl-1.18.2.jar:git-Pearl-"cf05459"]
        at org.bukkit.craftbukkit.v1_18_R2.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:962) ~[pearl-1.18.2.jar:git-Pearl-"cf05459"]
        at org.bukkit.craftbukkit.v1_18_R2.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:1183) ~[pearl-1.18.2.jar:git-Pearl-"cf05459"]
        at net.minecraft.world.entity.LivingEntity.damageEntity0(LivingEntity.java:2086) ~[?:?]
        at net.minecraft.world.entity.LivingEntity.hurt(LivingEntity.java:1353) ~[?:?]
        at net.minecraft.world.entity.animal.Wolf.doHurtTarget(Wolf.java:336) ~[?:?]
        at net.minecraft.world.entity.ai.goal.MeleeAttackGoal.checkAndPerformAttack(MeleeAttackGoal.java:130) ~[?:?]
        at net.minecraft.world.entity.ai.goal.MeleeAttackGoal.tick(MeleeAttackGoal.java:121) ~[?:?]
        at net.minecraft.world.entity.ai.goal.WrappedGoal.tick(WrappedGoal.java:63) ~[?:?]
        at net.minecraft.world.entity.ai.goal.GoalSelector.tickRunningGoals(GoalSelector.java:154) ~[?:?]
        at net.minecraft.world.entity.Mob.serverAiStep(Mob.java:853) ~[?:?]
        at net.minecraft.world.entity.LivingEntity.aiStep(LivingEntity.java:3296) ~[?:?]
        at net.minecraft.world.entity.Mob.aiStep(Mob.java:629) ~[?:?]
        at net.minecraft.world.entity.AgeableMob.aiStep(AgeableMob.java:154) ~[?:?]
        at net.minecraft.world.entity.animal.Animal.aiStep(Animal.java:61) ~[?:?]
        at net.minecraft.world.entity.animal.Wolf.aiStep(Wolf.java:203) ~[?:?]
        at net.minecraft.world.entity.LivingEntity.tick(LivingEntity.java:2938) ~[?:?]
        at net.minecraft.world.entity.Mob.tick(Mob.java:397) ~[?:?]
        at net.minecraft.world.entity.animal.Wolf.tick(Wolf.java:219) ~[?:?]
        at net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:1150) ~[?:?]
        at net.minecraft.server.level.ServerLevel.lambda$tick$5(ServerLevel.java:676) ~[?:?]
        at net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:42) ~[pearl-1.18.2.jar:git-Pearl-"cf05459"]
        at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:654) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1606) ~[pearl-1.18.2.jar:git-Pearl-"cf05459"]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:489) ~[pearl-1.18.2.jar:git-Pearl-"cf05459"]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1469) ~[pearl-1.18.2.jar:git-Pearl-"cf05459"]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1233) ~[pearl-1.18.2.jar:git-Pearl-"cf05459"]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:318) ~[pearl-1.18.2.jar:git-Pearl-"cf05459"]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassNotFoundException: org.bukkit.entity.Allay
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:153) ~[pearl-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:105) ~[pearl-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        ... 37 more

**To Reproduce**
1. Put plugin ecochant on serve
2. Then start server
3. Wait some miniute
4. And see error

**Server Information (please complete the following information):**
- Version of plugin and eco (`Eco: 6.37.3`, `ecoenchant 8.94.2`)

**Info server**
Pearl 1.18.2
JDK 17

**Comment by WillFP** [comment]
On it!
