### ISSUE TITLE
NetWork Protocol

### ISSUE THREAD

**Issue by TheCiROMG** [Auxilor/EcoEnchants#276]
```
[23:50:40 ERROR]: [eco] Unhandled exception occured in onPacketSending(PacketEvent) for eco
java.lang.NoSuchMethodError: 'com.comphenix.protocol.reflect.StructureModifier com.comphenix.protocol.reflect.StructureModifier.modify(int, java.util.function.UnaryOperator)'
        at com.willfp.eco.internal.spigot.display.PacketHeldWindowItems.onSend(PacketHeldWindowItems.kt:19) ~[eco-6.38.2-all.jar:?]
        at com.willfp.eco.core.AbstractPacketAdapter.onPacketSending(AbstractPacketAdapter.java:119) ~[eco-6.38.2-all.jar:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:535) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:516) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.ProtocolInjector.packetQueued(ProtocolInjector.java:346) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketSending(ProtocolInjector.java:308) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:436) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector.access$800(ChannelInjector.java:72) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector$3.handleScheduled(ChannelInjector.java:376) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector$3.onMessageScheduled(ChannelInjector.java:346) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:127) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:95) ~[ProtocolLib.jar:?]
        at net.minecraft.network.Connection.writePacket(Connection.java:423) ~[app:?]
        at net.minecraft.network.Connection.send(Connection.java:370) ~[app:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.send(ServerGamePacketListenerImpl.java:2079) ~[app:?]
        at xuan.cat.fartherviewdistance.code.branch.v17.Branch_17_ProxyPlayerConnection.a(Branch_17_ProxyPlayerConnection.java:110) ~[FartherViewDistance-9.1.1.jar:?]
        at xuan.cat.fartherviewdistance.code.branch.v17.Branch_17_ProxyPlayerConnection.sendPacket(Branch_17_ProxyPlayerConnection.java:86) ~[FartherViewDistance-9.1.1.jar:?]
        at net.minecraft.server.level.ServerPlayer$1.sendInitialData(ServerPlayer.java:282) ~[app:?]
        at net.minecraft.world.inventory.AbstractContainerMenu.sendAllDataToRemote(AbstractContainerMenu.java:194) ~[app:?]
        at org.bukkit.craftbukkit.v1_17_R1.entity.CraftPlayer.updateInventory(CraftPlayer.java:1115) ~[patched_1.17.1.jar:git-Purpur-1428]
        at net.skinsrestorer.bukkit.skinrefresher.SpigotSkinRefresher.accept(SpigotSkinRefresher.java:237) ~[SkinsRestorer.jar:?]
        at net.skinsrestorer.bukkit.skinrefresher.SpigotSkinRefresher.accept(SpigotSkinRefresher.java:41) ~[SkinsRestorer.jar:?]
        at net.skinsrestorer.bukkit.SkinApplierBukkit.lambda$updateSkin$4(SkinApplierBukkit.java:201) ~[SkinsRestorer.jar:?]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.17.1.jar:git-Purpur-1428]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[patched_1.17.1.jar:git-Purpur-1428]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1591) ~[patched_1.17.1.jar:git-Purpur-1428]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:528) ~[patched_1.17.1.jar:git-Purpur-1428]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1507) ~[patched_1.17.1.jar:git-Purpur-1428]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1300) ~[patched_1.17.1.jar:git-Purpur-1428]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:322) ~[patched_1.17.1.jar:git-Purpur-1428]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[23:50:40 ERROR]: Parameters:
  net.minecraft.network.protocol.game.PacketPlayOutWindowItems@499e1c65[
    a=0
    b=2
    c=[1 air, 1 air, 1 air, 1 air, 1 air, 1 diamond_helmet, 1 diamond_chestplate, 1 diamond_leggings, 1 diamond_boots, 64 baked_potato, 64 baked_potato, 64 baked_potato, 64 baked_potato, 4 spruce_planks, 52 bread, 43 spruce_log, 3 bone, 64 potato, 1 iron_shovel, 1 iron_pickaxe, 5 stick, 60 wheat_seeds, 61 potato, 14 wheat, 1 air, 1 air, 1 air, 1 air, 1 air, 1 air, 1 air, 1 air, 1 air, 1 air, 1 air, 1 air, 1 diamond_sword, 1 diamond_pickaxe, 1 diamond_axe, 13 cobbled_deepslate, 23 baked_potato, 1 air, 1 air, 1 air, 1 air, 28 torch]
    d=1 air
  ]
```

Minecraft 1.17.1

EcoEnchants and Eco up-to-date

Server in Java 17

**Comment by Yang-qwq** [comment]
see https://github.com/dmulloy2/ProtocolLib/issues/1469
