### ISSUE TITLE
Incompatibility between EcoEnchants & Skoice

### ISSUE THREAD

**Issue by TonyMontero** [Auxilor/EcoEnchants#311]
**Describe the bug**
Skoice + EcoEnchants break completely EcoEnchants not letting him to load.

**To Reproduce**
1. Install Skoice
2. Install Eco + EcoEnchants
3. Start the server
4. Profit

**Expected behavior**
Should work fine together, there is no reason to not work since they aren't even touching the same system.

**Server Information (please complete the following information):**
- Version:  Current: git-Purpur-1759 (MC: 1.19.2)*
- Version of plugin and eco: eco version 6.43.5 // EcoEnchants version 9.0.0-b39

**Screenshots**
```[23:50:32 WARN]: [EcoEnchants] Loaded class com.github.benmanes.caffeine.cache.Caffeine from StreamingDrops v10.6 which is not a depend or softdepend of this plugin.
[23:50:32 WARN]: org.bukkit.plugin.InvalidPluginException: java.lang.ClassCastException: class kotlin.io.FileTreeWalk cannot be cast to class kotlin.sequences.Sequence (kotlin.io.FileTreeWalk is in unnamed module of loader 'StreamingDrops_v.10.6.jar' @5eb5dd02; kotlin.sequences.Sequence is in unnamed module of loader 'Skoice.jar' @54934684)
[23:50:32 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:157)
[23:50:32 WARN]:        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:417)
[23:50:32 WARN]:        at PlugWoman.jar//redempt.plugwoman.PlugWoman.loadPlugin(PlugWoman.java:161)
[23:50:32 WARN]:        at PlugWoman.jar//redempt.plugwoman.CommandListener.loadPlugin(CommandListener.java:64)
[23:50:32 WARN]:        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[23:50:32 WARN]:        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[23:50:32 WARN]:        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[23:50:32 WARN]:        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[23:50:32 WARN]:        at PlugWoman.jar//libs.redempt.redlib.commandmanager.Command.runHook(Command.java:749)
[23:50:32 WARN]:        at PlugWoman.jar//libs.redempt.redlib.commandmanager.Command.execute(Command.java:654)
[23:50:32 WARN]:        at PlugWoman.jar//libs.redempt.redlib.commandmanager.Command.execute(Command.java:671)
[23:50:32 WARN]:        at PlugWoman.jar//libs.redempt.redlib.commandmanager.Command$1.execute(Command.java:437)
[23:50:32 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:168)
[23:50:32 WARN]:        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.dispatchCommand(CraftServer.java:942)
[23:50:32 WARN]:        at org.bukkit.craftbukkit.v1_19_R1.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64)
[23:50:32 WARN]:        at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:264)
[23:50:32 WARN]:        at net.minecraft.commands.CommandDispatcher.performCommand(CommandDispatcher.java:311)
[23:50:32 WARN]:        at net.minecraft.commands.CommandDispatcher.a(CommandDispatcher.java:295)
[23:50:32 WARN]:        at net.minecraft.server.network.PlayerConnection.b(PlayerConnection.java:2387)
[23:50:32 WARN]:        at net.minecraft.server.network.PlayerConnection.lambda$handleChatCommand$21(PlayerConnection.java:2341)
[23:50:32 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.b(IAsyncTaskHandler.java:59)
[23:50:32 WARN]:        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
[23:50:32 WARN]:        at net.minecraft.server.TickTask.run(TickTask.java:18)
[23:50:32 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
[23:50:32 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
[23:50:32 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1387)
[23:50:32 WARN]:        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:185)
[23:50:32 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.x(IAsyncTaskHandler.java:126)
[23:50:32 WARN]:        at net.minecraft.server.MinecraftServer.bh(MinecraftServer.java:1364)
[23:50:32 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1357)
[23:50:32 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.bq(IAsyncTaskHandler.java:114)
[23:50:32 WARN]:        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1491)
[23:50:32 WARN]:        at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1213)
[23:50:32 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:310)
[23:50:32 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[23:50:32 WARN]: Caused by: java.lang.ClassCastException: class kotlin.io.FileTreeWalk cannot be cast to class kotlin.sequences.Sequence (kotlin.io.FileTreeWalk is in unnamed module of loader 'StreamingDrops_v.10.6.jar' @5eb5dd02; kotlin.sequences.Sequence is in unnamed module of loader 'Skoice.jar' @54934684)
[23:50:32 WARN]:        at EcoEnchants v9.0.0-b39.jar//com.willfp.ecoenchants.enchants.EcoEnchant$3.invoke(EcoEnchant.kt:94)
[23:50:32 WARN]:        at EcoEnchants v9.0.0-b39.jar//com.willfp.ecoenchants.enchants.EcoEnchant$3.invoke(EcoEnchant.kt:89)
[23:50:32 WARN]:        at EcoEnchants v9.0.0-b39.jar//com.willfp.ecoenchants.enchants.EcoEnchant$config$2.invoke(EcoEnchant.kt:44)
[23:50:32 WARN]:        at EcoEnchants v9.0.0-b39.jar//com.willfp.ecoenchants.enchants.EcoEnchant$config$2.invoke(EcoEnchant.kt:44)
[23:50:32 WARN]:        at Skoice.jar//kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
[23:50:32 WARN]:        at EcoEnchants v9.0.0-b39.jar//com.willfp.ecoenchants.enchants.EcoEnchant.getConfig(EcoEnchant.kt:44)
[23:50:32 WARN]:        at EcoEnchants v9.0.0-b39.jar//com.willfp.ecoenchants.enchants.EcoEnchant.<init>(EcoEnchant.kt:50)
[23:50:32 WARN]:        at EcoEnchants v9.0.0-b39.jar//com.willfp.ecoenchants.enchants.EcoEnchant.<init>(EcoEnchant.kt:87)
[23:50:32 WARN]:        at EcoEnchants v9.0.0-b39.jar//com.willfp.ecoenchants.enchants.impl.EnchantmentTelekinesis.<init>(EnchantmentTelekinesis.kt:23)
[23:50:32 WARN]:        at EcoEnchants v9.0.0-b39.jar//com.willfp.ecoenchants.enchants.EcoEnchants.registerHardcodedEnchantments(EcoEnchants.kt:174)
[23:50:32 WARN]:        at EcoEnchants v9.0.0-b39.jar//com.willfp.ecoenchants.enchants.EcoEnchants.update(EcoEnchants.kt:107)
[23:50:32 WARN]:        at EcoEnchants v9.0.0-b39.jar//com.willfp.ecoenchants.EcoEnchantsPlugin.<init>(EcoEnchantsPlugin.kt:44)
[23:50:32 WARN]:        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[23:50:32 WARN]:        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
[23:50:32 WARN]:        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[23:50:32 WARN]:        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
[23:50:32 WARN]:        at java.base/java.lang.reflect.ReflectAccess.newInstance(ReflectAccess.java:128)
[23:50:32 WARN]:        at java.base/jdk.internal.reflect.ReflectionFactory.newInstance(ReflectionFactory.java:347)
[23:50:32 WARN]:        at java.base/java.lang.Class.newInstance(Class.java:645)
[23:50:32 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:85)
[23:50:32 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:153)
[23:50:32 WARN]:        ... 34 more```

**Comment by 0ft3n** [comment]
Skoice developers refused to cooperate so this plugin won't be compatible with ours

**Comment by TonyMontero** [comment]
What happened? They also told me they gave Skoice the way out to help but it was unable to cooperate with Skoice

**Comment by TonyMontero** [comment]
> Skoice developers refused to cooperate so this plugin won't be compatible with ours

Oh well, that's a shame, both are stupidly powerful

**Comment by carlodrift** [comment]
This was fixed a while ago btw!
