### ISSUE TITLE
Error in the "/ecoenchants gui" command

### ISSUE THREAD

**Issue by caipenghuo** [Auxilor/EcoEnchants#357]
**Describe the bug**
An internal error occurred while attempting to perform this command.

**Expected behavior**
The "/ecoenchants gui" command does not take effect correctly.

**Server Information (please complete the following information):**
- Version: git-Purpur-1858
- Version of plugin and eco : EcoEnchants v9.17.4        eco-6.52.2-all

**Additional context**
[16:40:00 INFO]: KatouMegumi issued server command: /ecoenchants gui
[16:40:00 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'ecoenchants' in plugin EcoEnchants v9.17.4
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:168) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.dispatchCommand(CraftServer.java:962) ~[purpur-1.19.2.jar:git-Purpur-1858]
        at org.bukkit.craftbukkit.v1_19_R1.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64) ~[purpur-1.19.2.jar:git-Purpur-1858]
        at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:264) ~[purpur-1.19.2.jar:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:313) ~[?:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:297) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.performChatCommand(ServerGamePacketListenerImpl.java:2386) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$21(ServerGamePacketListenerImpl.java:2340) ~[?:?]
        at net.minecraft.util.thread.BlockableEventLoop.lambda$submitAsync$0(BlockableEventLoop.java:59) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.19.2.jar:git-Purpur-1858]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1368) ~[purpur-1.19.2.jar:git-Purpur-1858]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:185) ~[purpur-1.19.2.jar:git-Purpur-1858]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1345) ~[purpur-1.19.2.jar:git-Purpur-1858]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1338) ~[purpur-1.19.2.jar:git-Purpur-1858]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1316) ~[purpur-1.19.2.jar:git-Purpur-1858]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1204) ~[purpur-1.19.2.jar:git-Purpur-1858]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:310) ~[purpur-1.19.2.jar:git-Purpur-1858]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: kotlin.UninitializedPropertyAccessException: lateinit property menu has not been initialized
        at com.willfp.ecoenchants.enchants.EnchantGUI.openGUI(EnchantGUI.kt:149) ~[EcoEnchants v9.17.4.jar:?]
        at com.willfp.ecoenchants.commands.CommandGUI.onExecute(CommandGUI.kt:12) ~[EcoEnchants v9.17.4.jar:?]
        at com.willfp.eco.internal.command.HandledCommand.handleExecution(HandledCommand.kt:111) ~[eco-6.52.2-all.jar:?]
        at com.willfp.eco.internal.command.HandledCommand.handleExecution(HandledCommand.kt:102) ~[eco-6.52.2-all.jar:?]
        at com.willfp.eco.internal.command.HandledCommand.onCommand(HandledCommand.kt:42) ~[eco-6.52.2-all.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        ... 23 more

**Comment by caipenghuo** [comment]
[13:52:50 ERROR]: [EcoEnchants] Update method public static final void com.willfp.ecoenchants.enchants.EnchantGUI.update(com.willfp.ecoenchants.EcoEnchantsPlugin) generated an exception
[13:52:50 WARN]: [EcoEnchants] 1 enchantments were not loaded because they need EcoBosses to be installed!
[13:52:50 WARN]: [EcoEnchants] Either download EcoBosses or delete the folder at /plugins/EcoEnchants/enchants/ecobosses to remove this message
[13:52:50 WARN]: [EcoEnchants] 1 enchantments were not loaded because they need EcoJobs to be installed!
[13:52:50 WARN]: [EcoEnchants] Either download EcoJobs or delete the folder at /plugins/EcoEnchants/enchants/ecojobs to remove this message
[13:52:50 WARN]: [EcoEnchants] 1 enchantments were not loaded because they need EcoPets to be installed!
[13:52:50 WARN]: [EcoEnchants] Either download EcoPets or delete the folder at /plugins/EcoEnchants/enchants/ecopets to remove this message
[13:52:50 WARN]: [EcoEnchants] 19 enchantments were not loaded because they need EcoSkills to be installed!
[13:52:50 WARN]: [EcoEnchants] Either download EcoSkills or delete the folder at /plugins/EcoEnchants/enchants/ecoskills to remove this message
[13:52:51 WARN]: java.lang.reflect.InvocationTargetException
[13:52:51 WARN]:        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[13:52:51 WARN]:        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[13:52:51 WARN]:        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[13:52:51 WARN]:        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[13:52:51 WARN]:        at eco-6.52.2-all.jar//com.willfp.eco.internal.config.EcoConfigHandler.callUpdate(EcoConfigHandler.kt:25)
[13:52:51 WARN]:        at eco-6.52.2-all.jar//com.willfp.eco.core.EcoPlugin.reload(EcoPlugin.java:577)
[13:52:51 WARN]:        at eco-6.52.2-all.jar//com.willfp.eco.core.EcoPlugin.afterLoad(EcoPlugin.java:551)
[13:52:51 WARN]:        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101)
[13:52:51 WARN]:        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483)
[13:52:51 WARN]:        at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1130)
[13:52:51 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:310)
[13:52:51 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[13:52:51 WARN]:

 Caused by: java.lang.LinkageError: loader constraint violation: when resolving method 'com.willfp.eco.core.gui.menu.Menu com.willfp.eco.core.gui.GUIHelperExtensions.menu(int, kotlin.jvm.functions.Function1)' the class loader 'EcoEnchants v9.17.4.jar' @775f2620 of the current class, com/willfp/ecoenchants/enchants/EnchantGUI, and the class loader 'eco-6.52.2-all.jar' @2cb108e8 for the method's defining class, com/willfp/eco/core/gui/GUIHelperExtensions, have different Class objects for the type kotlin/jvm/functions/Function1 used in the signature (com.willfp.ecoenchants.enchants.EnchantGUI is in unnamed module of loader 'EcoEnchants v9.17.4.jar' @775f2620, parent loader java.net.URLClassLoader @73a8dfcc; com.willfp.eco.core.gui.GUIHelperExtensions is in unnamed module of loader 'eco-6.52.2-all.jar' @2cb108e8, parent loader java.net.URLClassLoader @73a8dfcc)


[13:52:51 WARN]:        at EcoEnchants v9.17.4.jar//com.willfp.ecoenchants.enchants.EnchantGUI.update(EnchantGUI.kt:43)
[13:52:51 WARN]:        ... 12 more
