### ISSUE TITLE
An error occurred

### ISSUE THREAD

**Issue by xiaofengv233** [Auxilor/EcoEnchants#370]
Provider.kt:149) ~[[E][更多附魔]EcoEnchants v10.17.0.jar:?]
        at com.willfp.libreforge.HolderProviderKt.generatePlaceholders(HolderProvider.kt:175) ~[libreforge-4.17.0.jar:?]
        at com.willfp.libreforge.ProvidedHolderConfigKt.applyHolder(ProvidedHolderConfig.kt:39) ~[libreforge-4.17.0.jar:?]
        at com.willfp.libreforge.conditions.ConditionBlock.isMet(ConditionBlock.kt:33) ~[libreforge-4.17.0.jar:?]
        at com.willfp.libreforge.conditions.ConditionList.areMet(ConditionList.kt:20) ~[libreforge-4.17.0.jar:?]
        at com.willfp.ecoenchants.target.EnchantLookup.getActiveEnchantsInSlots(EnchantLookup.kt:184) ~[[E][更多附魔]EcoEnchants v10.17.0.jar:?]
        at com.willfp.ecoenchants.target.EnchantLookup.getActiveEnchants(EnchantLookup.kt:200) ~[[E][更多附魔]EcoEnchants v10.17.0.jar:?]
        at com.willfp.ecoenchants.target.EnchantLookup.getActiveEnchantLevel(EnchantLookup.kt:224) ~[[E][更多附魔]EcoEnchants v10.17.0.jar:?]
        at com.willfp.ecoenchants.EcoEnchantsPlugin$handleEnable$$inlined$registerHolderPlaceholderProvider$1.invoke(HolderProvider.kt:361) ~[[E][更多附魔]EcoEnchants v10.17.0.jar:?]
        at com.willfp.ecoenchants.EcoEnchantsPlugin$handleEnable$$inlined$registerHolderPlaceholderProvider$1.invoke(HolderProvider.kt:149) ~[[E][更多附魔]EcoEnchants v10.17.0.jar:?]
        at com.willfp.libreforge.HolderProviderKt.generatePlaceholders(HolderProvider.kt:175) ~[libreforge-4.17.0.jar:?]
        at com.willfp.libreforge.ProvidedHolderConfigKt.applyHolder(ProvidedHolderConfig.kt:39) ~[libreforge-4.17.0.jar:?]
        at com.willfp.libreforge.conditions.ConditionBlock.isMet(ConditionBlock.kt:33) ~[libreforge-4.17.0.jar:?]
        at com.willfp.libreforge.conditions.ConditionList.areMet(ConditionList.kt:20) ~[libreforge-4.17.0.jar:?]
        at com.willfp.ecoenchants.target.EnchantLookup.getActiveEnchantsInSlots(EnchantLookup.kt:184) ~[[E][更多附魔]EcoEnchants v10.17.0.jar:?]
        at com.willfp.ecoenchants.target.EnchantLookup.getActiveEnchants(EnchantLookup.kt:200) ~[[E][更多附魔]EcoEnchants v10.17.0.jar:?]
        at com.willfp.ecoenchants.target.EnchantLookup.getActiveEnchantLevel(EnchantLookup.kt:224) ~[[E][更多附魔]EcoEnchants v10.17.0.jar:?]
        at com.willfp.ecoenchants.EcoEnchantsPlugin$handleEnable$$inlined$registerHolderPlaceholderProvider$1.invoke(HolderProvider.kt:361) ~[[E][更多附魔]EcoEnchants v10.17.0.jar:?]
        at com.willfp.ecoenchants.EcoEnchantsPlugin$handleEnable$$inlined$registerHolderPlaceholderProvider$1.invoke(HolderProvider.kt:149) ~[[E][更多附魔]EcoEnchants v10.17.0.jar:?]
        at com.willfp.libreforge.HolderProviderKt.generatePlaceholders(HolderProvider.kt:175) ~[libreforge-4.17.0.jar:?]
        at com.willfp.libreforge.ProvidedHolderConfigKt.applyHolder(ProvidedHolderConfig.kt:39) ~[libreforge-4.17.0.jar:?]
        at com.willfp.libreforge.conditions.ConditionBlock.isMet(ConditionBlock.kt:33) ~[libreforge-4.17.0.jar:?]
        at com.willfp.libreforge.conditions.ConditionList.areMet(ConditionList.kt:20) ~[libreforge-4.17.0.jar:?]
        at com.willfp.ecoenchants.target.EnchantLookup.getActiveEnchantsInSlots(EnchantLookup.kt:184) ~[[E][更多附魔]EcoEnchants v10.17.0.jar:?]
        at com.willfp.ecoenchants.target.EnchantLookup.getActiveEnchants(EnchantLookup.kt:200) ~[[E][更多附魔]EcoEnchants v10.17.0.jar:?]
        at com.willfp.ecoenchants.target.EnchantLookup.getActiveEnchantLevel(EnchantLookup.kt:224) ~[[E][更多附魔]EcoEnchants v10.17.0.jar:?]
        at com.willfp.ecoenchants.EcoEnchantsPlugin$handleEnable$$inlined$registerHolderPlaceholderProvider$1.invoke(HolderProvider.kt:361) ~[[E][更多附魔]EcoEnchants v10.17.0.jar:?]
        at com.willfp.ecoenchants.EcoEnchantsPlugin$handleEnable$$inlined$registerHolderPlaceholderProvider$1.invoke(HolderProvider.kt:149) ~[[E][更多附魔]EcoEnchants v10.17.0.jar:?]
        at com.willfp.libreforge.HolderProviderKt.generatePlaceholders(HolderProvider.kt:175) ~[libreforge-4.17.0.jar:?]
        at com.willfp.libreforge.ProvidedHolderConfigKt.applyHolder(ProvidedHolderConfig.kt:39) ~[libreforge-4.17.0.jar:?]
        at com.willfp.libreforge.conditions.ConditionBlock.isMet(ConditionBlock.kt:33) ~[libreforge-4.17.0.jar:?]
        at com.willfp.libreforge.conditions.ConditionList.areMet(ConditionList.kt:20) ~[libreforge-4.17.0.jar:?]
        at com.willfp.ecoenchants.target.EnchantLookup.getActiveEnchantsInSlots(EnchantLookup.kt:184) ~[[E][更多附魔]EcoEnchants v10.17.0.jar:?]
        at com.willfp.ecoenchants.target.EnchantLookup.getActiveEnchants(EnchantLookup.kt:200) ~[[E][更多附魔]EcoEnchants v10.17.0.jar:?]
        at com.willfp.ecoenchants.target.EnchantLookup.getActiveEnchantLevel(EnchantLookup.kt:224) ~[[E][更多附魔]EcoEnchants v10.17.0.jar:?]
        at com.willfp.ecoenchants.EcoEnchantsPlugin$handleEnable$$inlined$registerHolderPlaceholderProvider$1.invoke(HolderProvider.kt:361) ~[[E][更多附魔]EcoEnchants v10.17.0.jar:?]
        at com.willfp.ecoenchants.EcoEnchantsPlugin$handleEnable$$inlined$registerHolderPlaceholderProvider$1.invoke(HolderProvider.kt:149) ~[[E][更多附魔]EcoEnchants v10.17.0.jar:?]
        at com.willfp.libreforge.HolderProviderKt.generatePlaceholders(HolderProvider.kt:175) ~[libreforge-4.17.0.jar:?]
        at com.willfp.libreforge.ProvidedHolderConfigKt.applyHolder(ProvidedHolderConfig.kt:39) ~[libreforge-4.17.0.jar:?]
        at com.willfp.libreforge.conditions.ConditionBlock.isMet(ConditionBlock.kt:33) ~[libreforge-4.17.0.jar:?]
        at com.willfp.libreforge.conditions.ConditionList.areMet(ConditionList.kt:20) ~[libreforge-4.17.0.jar:?]
        at com.willfp.ecoenchants.target.EnchantLookup.getActiveEnchantsInSlots(EnchantLookup.kt:184) ~[[E][更多附魔]EcoEnchants v10.17.0.jar:?]
        at com.willfp.ecoenchants.target.EnchantLookup.getActiveEnchants(EnchantLookup.kt:200) ~[[E][更多附魔]EcoEnchants v10.17.0.jar:?]
        at com.willfp.ecoenchants.target.EnchantLookup.getActiveEnchantLevel(EnchantLookup.kt:224) ~[[E][更多附魔]EcoEnchants v10.17.0.jar:?]
        at com.willfp.ecoenchants.EcoEnchantsPlugin$handleEnable$$inlined$registerHolderPlaceholderProvider$1.invoke(HolderProvider.kt:361) ~[[E][更多附魔]EcoEnchants v10.17.0.jar:?]
        at com.willfp.ecoenchants.EcoEnchantsPlugin$handleEnable$$inlined$registerHolderPlaceholderProvider$1.invoke(HolderProvider.kt:149) ~[[E][更多附魔]EcoEnchants v10.17.0.jar:?]
        at com.willfp.libreforge.HolderProviderKt.generatePlaceholders(HolderProvider.kt:175) ~[libreforge-4.17.0.jar:?]
        at com.willfp.libreforge.ProvidedHolderConfigKt.applyHolder(ProvidedHolderConfig.kt:39) ~[libreforge-4.17.0.jar:?]
        at com.willfp.libreforge.conditions.ConditionBlock.isMet(ConditionBlock.kt:33) ~[libreforge-4.17.0.jar:?]
        at com.willfp.libreforge.conditions.ConditionList.areMet(ConditionList.kt:20) ~[libreforge-4.17.0.jar:?]
        at com.willfp.ecoenchants.target.EnchantLookup.getActiveEnchantsInSlots(EnchantLookup.kt:184) ~[[E][更多附魔]EcoEnchants v10.17.0.jar:?]
        at com.willfp.ecoenchants.target.EnchantLookup.getActiveEnchants(EnchantLookup.kt:200) ~[[E][更多附魔]EcoEnchants v10.17.0.jar:?]
        at com.willfp.ecoenchants.target.EnchantLookup.getActiveEnchantLevel(EnchantLookup.kt:224) ~[[E][更多附魔]EcoEnchants v10.17.0.jar:?]
        at com.willfp.ecoenchants.EcoEnchantsPlugin$handleEnable$$inlined$registerHolderPlaceholderProvider$1.invoke(HolderProvider.kt:361) ~[[E][更多附魔]EcoEnchants v10.17.0.jar:?]
        at com.willfp.ecoenchants.EcoEnchantsPlugin$handleEnable$$inlined$registerHolderPlaceholderProvider$1.invoke(HolderProvider.kt:149) ~[[E][更多附魔]EcoEnchants v10.17.0.jar:?]
        at com.willfp.libreforge.HolderProviderKt.generatePlaceholders(HolderProvider.kt:175) ~[libreforge-4.17.0.jar:?]
        at com.willfp.libreforge.ProvidedHolderConfigKt.applyHolder(ProvidedHolderConfig.kt:39) ~[libreforge-4.17.0.jar:?]
        at com.willfp.libreforge.conditions.ConditionBlock.isMet(ConditionBlock.kt:33) ~[libreforge-4.17.0.jar:?]
        at com.willfp.libreforge.conditions.ConditionList.areMet(ConditionList.kt:20) ~[libreforge-4.17.0.jar:?]
        at com.willfp.ecoenchants.target.EnchantLookup.getActiveEnchantsInSlots(EnchantLookup.kt:184) ~[[E][更多附魔]EcoEnchants v10.17.0.jar:?]
        at com.willfp.ecoenchants.target.EnchantLookup.getActiveEnchants(EnchantLookup.kt:200) ~[[E][更多附魔]EcoEnchants v10.17.0.jar:?]
        at com.willfp.ecoenchants.target.EnchantLookup.getActiveEnchantLevel(EnchantLookup.kt:224) ~[[E][更多附魔]EcoEnchants v10.17.0.jar:?]
        at com.willfp.ecoenchants.EcoEnchantsPlugin$handleEnable$$inlined$registerHolderPlaceholderProvider$1.invoke(HolderProvider.kt:361) ~[[E][更多附魔]EcoEnchants v10.17.0.jar:?]
        at com.willfp.ecoenchants.EcoEnchantsPlugin$handleEnable$$inlined$registerHolderPlaceholderProvider$1.invoke(HolderProvider.kt:149) ~[[E][更多附魔]EcoEnchants v10.17.0.jar:?]
        at com.willfp.libreforge.HolderProviderKt.generatePlaceholders(HolderProvider.kt:175) ~[libreforge-4.17.0.jar:?]
        at com.willfp.libreforge.ProvidedHolderConfigKt.applyHolder(ProvidedHolderConfig.kt:39) ~[libreforge-4.17.0.jar:?]
        at com.willfp.libreforge.conditions.ConditionBlock.isMet(ConditionBlock.kt:33) ~[libreforge-4.17.0.jar:?]
        at com.willfp.libreforge.conditions.ConditionList.areMet(ConditionList.kt:20) ~[libreforge-4.17.0.jar:?]
        at com.willfp.ecoenchants.target.EnchantLookup.getActiveEnchantsInSlots(EnchantLookup.kt:184) ~[[E][更多附魔]EcoEnchants v10.17.0.jar:?]
        at com.willfp.ecoenchants.target.EnchantLookup.getActiveEnchants(EnchantLookup.kt:200) ~[[E][更多附魔]EcoEnchants v10.17.0.jar:?]
        at com.willfp.ecoenchants.target.EnchantLookup.getActiveEnchantLevel(EnchantLookup.kt:224) ~[[E][更多附魔]EcoEnchants v10.17.0.jar:?]
        at com.willfp.ecoenchants.EcoEnchantsPlugin$handleEnable$$inlined$registerHolderPlaceholderProvider$1.invoke(HolderProvider.kt:361) ~[[E][更多附魔]EcoEnchants v10.17.0.jar:?]
        at com.willfp.ecoenchants.EcoEnchantsPlugin$handleEnable$$inlined$registerHolderPlaceholderProvider$1.invoke(HolderProvider.kt:149) ~[[E][更多附魔]EcoEnchants v10.17.0.jar:?]
        at com.willfp.libreforge.HolderProviderKt.generatePlaceholders(HolderProvider.kt:175) ~[libreforge-4.17.0.jar:?]
        at com.willfp.libreforge.ProvidedHolderConfigKt.applyHolder(ProvidedHolderConfig.kt:39) ~[libreforge-4.17.0.jar:?]
        at com.willfp.libreforge.conditions.ConditionBlock.isMet(ConditionBlock.kt:33) ~[libreforge-4.17.0.jar:?]
        at com.willfp.libreforge.conditions.ConditionList.areMet(ConditionList.kt:20) ~[libreforge-4.17.0.jar:?]
        at com.willfp.ecoenchants.target.EnchantLookup.getActiveEnchantsInSlots(EnchantLookup.kt:184) ~[[E][更多附魔]EcoEnchants v10.17.0.jar:?]
        at com.willfp.ecoenchants.target.EnchantLookup.getActiveEnchants(EnchantLookup.kt:200) ~[[E][更多附魔]EcoEnchants v10.17.0.jar:?]
        at com.willfp.ecoenchants.target.EnchantLookup.getActiveEnchantLevel(EnchantLookup.kt:224) ~[[E][更多附魔]EcoEnchants v10.17.0.jar:?]
        at com.willfp.ecoenchants.EcoEnchantsPlugin$handleEnable$$inlined$registerHolderPlaceholderProvider$1.invoke(HolderProvider.kt:361) ~[[E][更多附魔]EcoEnchants v10.17.0.jar:?]
        at com.willfp.ecoenchants.EcoEnchantsPlugin$handleEnable$$inlined$registerHolderPlaceholderProvider$1.invoke(HolderProvider.kt:149) ~[[E][更多附魔]EcoEnchants v10.17.0.jar:?]
        at com.willfp.libreforge.HolderProviderKt.generatePlaceholders(HolderProvider.kt:175) ~[libreforge-4.17.0.jar:?]
        at com.willfp.libreforge.ProvidedHolderConfigKt.applyHolder(ProvidedHolderConfig.kt:39) ~[libreforge-4.17.0.jar:?]
        at com.willfp.libreforge.conditions.ConditionBlock.isMet(ConditionBlock.kt:33) ~[libreforge-4.17.0.jar:?]
        at com.willfp.libreforge.conditions.ConditionList.areMet(ConditionList.kt:20) ~[libreforge-4.17.0.jar:?]
        at com.willfp.ecoenchants.target.EnchantLookup.getActiveEnchantsInSlots(EnchantLookup.kt:184) ~[[E][更多附魔]EcoEnchants v10.17.0.jar:?]
        at com.willfp.ecoenchants.target.EnchantLookup.getActiveEnchants(EnchantLookup.kt:200) ~[[E][更多附魔]EcoEnchants v10.17.0.jar:?]
        at com.willfp.ecoenchants.target.EnchantLookup.getActiveEnchantLevel(EnchantLookup.kt:224) ~[[E][更多附魔]EcoEnchants v10.17.0.jar:?]
        at com.willfp.ecoenchants.EcoEnchantsPlugin$handleEnable$$inlined$registerHolderPlaceholderProvider$1.invoke(HolderProvider.kt:361) ~[[E][更多附魔]EcoEnchants v10.17.0.jar:?]
        at com.willfp.ecoenchants.EcoEnchantsPlugin$handleEnable$$inlined$registerHolderPlaceholderProvider$1.invoke(HolderProvider.kt:149) ~[[E][更多附魔]EcoEnchants v10.17.0.jar:?]
        at com.willfp.libreforge.HolderProviderKt.generatePlaceholders(HolderProvider.kt:175) ~[libreforge-4.17.0.jar:?]
        at com.willfp.libreforge.ProvidedHolderConfigKt.applyHolder(ProvidedHolderConfig.kt:39) ~[libreforge-4.17.0.jar:?]
        at com.willfp.libreforge.conditions.ConditionBlock.isMet(ConditionBlock.kt:33) ~[libreforge-4.17.0.jar:?]
        at com.willfp.libreforge.conditions.ConditionList.areMet(ConditionList.kt:20) ~[libreforge-4.17.0.jar:?]
        at com.willfp.ecoenchants.target.EnchantLookup.getActiveEnchantsInSlots(EnchantLookup.kt:184) ~[[E][更多附魔]EcoEnchants v10.17.0.jar:?]
        at com.willfp.ecoenchants.target.EnchantLookup.getActiveEnchants(EnchantLookup.kt:200) ~[[E][更多附魔]EcoEnchants v10.17.0.jar:?]
        at com.willfp.ecoenchants.target.EnchantLookup.getActiveEnchantLevel(EnchantLookup.kt:224) ~[[E][更多附魔]EcoEnchants v10.17.0.jar:?]
        at com.willfp.ecoenchants.EcoEnchantsPlugin$handleEnable$$inlined$registerHolderPlaceholderProvider$1.invoke(HolderProvider.kt:361) ~[[E][更多附魔]EcoEnchants v10.17.0.jar:?]
        at com.willfp.ecoenchants.EcoEnchantsPlugin$handleEnable$$inlined$registerHolderPlaceholderProvider$1.invoke(HolderProvider.kt:149) ~[[E][更多附魔]EcoEnchants v10.17.0.jar:?]
        at com.willfp.libreforge.HolderProviderKt.generatePlaceholders(HolderProvider.kt:175) ~[libreforge-4.17.0.jar:?]
        at com.willfp.libreforge.ProvidedHolderConfigKt.applyHolder(ProvidedHolderConfig.kt:39) ~[libreforge-4.17.0.jar:?]
        at com.willfp.libreforge.conditions.ConditionBlock.isMet(ConditionBlock.kt:33) ~[libreforge-4.17.0.jar:?]
        at com.willfp.libreforge.conditions.ConditionList.areMet(ConditionList.kt:20) ~[libreforge-4.17.0.jar:?]
        at com.willfp.ecoenchants.target.EnchantLookup.getActiveEnchantsInSlots(EnchantLookup.kt:184) ~[[E][更多附魔]EcoEnchants v10.17.0.jar:?]
        at com.willfp.ecoenchants.target.EnchantLookup.getActiveEnchants(EnchantLookup.kt:200) ~[[E][更多附魔]EcoEnchants v10.17.0.jar:?]
        at com.willfp.ecoenchants.target.EnchantLookup.getActiveEnchantLevel(EnchantLookup.kt:224) ~[[E][更多附魔]EcoEnchants v10.17.0.jar:?]
        at com.willfp.ecoenchants.EcoEnchantsPlugin$handleEnable$$inlined$registerHolderPlaceholderProvider$1.invoke(HolderProvider.kt:361) ~[[E][更多附魔]EcoEnchants v10.17.0.jar:?]
        at com.willfp.ecoenchants.EcoEnchantsPlugin$handleEnable$$inlined$registerHolderPlaceholderProvider$1.invoke(HolderProvider.kt:149) ~[[E][更多附魔]EcoEnchants v10.17.0.jar:?]
        at com.willfp.libreforge.HolderProviderKt.generatePlaceholders(HolderProvider.kt:175) ~[libreforge-4.17.0.jar:?]
        at com.willfp.libreforge.ProvidedHolderConfigKt.applyHolder(ProvidedHolderConfig.kt:39) ~[libreforge-4.17.0.jar:?]
        at com.willfp.libreforge.conditions.ConditionBlock.isMet(ConditionBlock.kt:33) ~[libreforge-4.17.0.jar:?]
        at com.willfp.libreforge.conditions.ConditionList.areMet(ConditionList.kt:20) ~[libreforge-4.17.0.jar:?]
        at com.willfp.ecoenchants.target.EnchantLookup.getActiveEnchantsInSlots(EnchantLookup.kt:184) ~[[E][更多附魔]EcoEnchants v10.17.0.jar:?]
        at com.willfp.ecoenchants.target.EnchantLookup.getActiveEnchants(EnchantLookup.kt:200) ~[[E][更多附魔]EcoEnchants v10.17.0.jar:?]
        at com.willfp.ecoenchants.target.EnchantLookup.getActiveEnchantLevel(EnchantLookup.kt:224) ~[[E][更多附魔]EcoEnchants v10.17.0.jar:?]
        at com.willfp.ecoenchants.EcoEnchantsPlugin$handleEnable$$inlined$registerHolderPlaceholderProvider$1.invoke(HolderProvider.kt:361) ~[[E][更多附魔]EcoEnchants v10.17.0.jar:?]
        at com.willfp.ecoenchants.EcoEnchantsPlugin$handleEnable$$inlined$registerHolderPlaceholderProvider$1.invoke(HolderProvider.kt:149) ~[[E][更多附魔]EcoEnchants v10.17.0.jar:?]
        at com.willfp.libreforge.HolderProviderKt.generatePlaceholders(HolderProvider.kt:175) ~[libreforge-4.17.0.jar:?]
        at com.willfp.libreforge.ProvidedHolderConfigKt.applyHolder(ProvidedHolderConfig.kt:39) ~[libreforge-4.17.0.jar:?]
        at com.willfp.libreforge.conditions.ConditionBlock.isMet(ConditionBlock.kt:33) ~[libreforge-4.17.0.jar:?]
        at com.willfp.libreforge.conditions.ConditionList.areMet(ConditionList.kt:20) ~[libreforge-4.17.0.jar:?]
        at com.willfp.ecoenchants.target.EnchantLookup.getActiveEnchantsInSlots(EnchantLookup.kt:184) ~[[E][更多附魔]EcoEnchants v10.17.0.jar:?]
        at com.willfp.ecoenchants.target.EnchantLookup.getActiveEnchants(EnchantLookup.kt:200) ~[[E][更多附魔]EcoEnchants v10.17.0.jar:?]
        at com.willfp.ecoenchants.target.EnchantLookup.getActiveEnchantLevel(EnchantLookup.kt:224) ~[[E][更多附魔]EcoEnchants v10.17.0.jar:?]
        at com.willfp.ecoenchants.EcoEnchantsPlugin$handleEnable$$inlined$registerHolderPlaceholderProvider$1.invoke(HolderProvider.kt:361) ~[[E][更多附魔]EcoEnchants v10.17.0.jar:?]
        at com.willfp.ecoenchants.EcoEnchantsPlugin$handleEnable$$inlined$registerHolderPlaceholderProvider$1.invoke(HolderProvider.kt:149) ~[[E][更多附魔]EcoEnchants v10.17.0.jar:?]
        at com.willfp.libreforge.HolderProviderKt.generatePlaceholders(HolderProvider.kt:175) ~[libreforge-4.17.0.jar:?]
        at com.willfp.libreforge.ProvidedHolderConfigKt.applyHolder(ProvidedHolderConfig.kt:39) ~[libreforge-4.17.0.jar:?]

**Comment by xiaofengv233** [comment]
10.16.0 does not have this bug
Available since 10.16.1
10.17.0 also has
