### ISSUE TITLE
ModifiedVanillaCraftEnchantment.conflictsWith(ModifiedVanillaCraftEnchantment

### ISSUE THREAD

**Issue by AkariH** [Auxilor/EcoEnchants#390]
[EcoEnchants] Task #414938421 for EcoEnchants v12.4.0 generated an exception
java.lang.StackOverflowError: null
	at com.willfp.ecoenchants.proxy.v1_20_R3.registration.ModifiedVanillaCraftEnchantment.conflictsWith(ModifiedVanillaCraftEnchantment.kt:17) ~[EcoEnchants v12.4.0.jar:?]
	at com.willfp.ecoenchants.proxy.v1_20_R3.registration.ModifiedVanillaCraftEnchantment.conflictsWith(ModifiedVanillaCraftEnchantment.kt:17) ~[EcoEnchants v12.4.0.jar:?]
	at com.willfp.ecoenchants.proxy.v1_20_R3.registration.ModifiedVanillaCraftEnchantment.conflictsWith(ModifiedVanillaCraftEnchantment.kt:17) ~[EcoEnchants v12.4.0.jar:?]
	at com.willfp.ecoenchants.proxy.v1_20_R3.registration.ModifiedVanillaCraftEnchantment.conflictsWith(ModifiedVanillaCraftEnchantment.kt:17) ~[EcoEnchants v12.4.0.jar:?]
	at com.willfp.ecoenchants.proxy.v1_20_R3.registration.ModifiedVanillaCraftEnchantment.conflictsWith(ModifiedVanillaCraftEnchantment.kt:17) ~[EcoEnchants v12.4.0.jar:?]
	at com.willfp.ecoenchants.proxy.v1_20_R3.registration.ModifiedVanillaCraftEnchantment.conflictsWith(ModifiedVanillaCraftEnchantment.kt:17) ~[EcoEnchants v12.4.0.jar:?]

**Comment by AkariH** [comment]
Some vanilla enchantments are conflicting with each other.
