### ISSUE TITLE
Why proxies don't work???

### ISSUE THREAD

**Issue by Ericlyclyclyc** [Auxilor/EcoEnchants#405]
I'm using Purpur+Velocity.
Purpur version:`[00:26:39 INFO]: Current Purpur Version: 1.21.3-2358-16ce24a (MC: 1.21.3)`
Velocity version:`[00:29:12 INFO]: Velocity 3.4.0-SNAPSHOT (git-4aa9ee77-b455)`

and recieve this:
```
[00:16:21 ERROR]: [EcoEnchants] Fatal error with proxies! This plugin can't load.
[00:16:21 ERROR]: [ModernPluginLoadingStrategy] Could not load plugin 'EcoEnchants_v12.3.0.jar' in folder 'plugins\.paper-remapped'
org.bukkit.plugin.InvalidPluginException: Exception initializing main class `com.willfp.ecoenchants.EcoEnchantsPlugin'
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:108) ~[purpur-api-1.21.3-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProvider.createInstance(SpigotPluginProvider.java:125) ~[purpur-1.21.3.jar:1.21.3-2358-16ce24a]
        at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProvider.createInstance(SpigotPluginProvider.java:35) ~[purpur-1.21.3.jar:1.21.3-2358-16ce24a]
        at io.papermc.paper.plugin.entrypoint.strategy.modern.ModernPluginLoadingStrategy.loadProviders(ModernPluginLoadingStrategy.java:116) ~[purpur-1.21.3.jar:1.21.3-2358-16ce24a]
        at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:38) ~[purpur-1.21.3.jar:1.21.3-2358-16ce24a]
        at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:40) ~[purpur-1.21.3.jar:1.21.3-2358-16ce24a]
        at org.bukkit.craftbukkit.CraftServer.loadPlugins(CraftServer.java:575) ~[purpur-1.21.3.jar:1.21.3-2358-16ce24a]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:326) ~[purpur-1.21.3.jar:1.21.3-2358-16ce24a]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1251) ~[purpur-1.21.3.jar:1.21.3-2358-16ce24a]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:344) ~[purpur-1.21.3.jar:1.21.3-2358-16ce24a]
        at java.base/java.lang.Thread.run(Thread.java:1575) ~[?:?]
Caused by: java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:74) ~[?:?]
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:501) ~[?:?]
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:485) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:100) ~[purpur-api-1.21.3-R0.1-SNAPSHOT.jar:?]
        ... 10 more
Caused by: com.willfp.eco.core.proxy.exceptions.ProxyError: Could not initialize proxy. Are you running a supported server version?
        at eco-6.74.5-all.jar/com.willfp.eco.internal.proxy.EcoProxyFactory.proxyErrorFrom(EcoProxyFactory.kt:52) ~[eco-6.74.5-all.jar:?]
        at eco-6.74.5-all.jar/com.willfp.eco.internal.proxy.EcoProxyFactory.getProxy(EcoProxyFactory.kt:37) ~[eco-6.74.5-all.jar:?]
        at eco-6.74.5-all.jar/com.willfp.eco.core.EcoPlugin.getProxy(EcoPlugin.java:967) ~[eco-6.74.5-all.jar:?]
        at EcoEnchants_v12.3.0.jar/com.willfp.ecoenchants.EcoEnchantsPlugin.<init>(EcoEnchantsPlugin.kt:57) ~[EcoEnchants_v12.3.0.jar:?]
        at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62) ~[?:?]
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:501) ~[?:?]
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:485) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:100) ~[purpur-api-1.21.3-R0.1-SNAPSHOT.jar:?]
        ... 10 more
Caused by: java.lang.ClassNotFoundException: com.willfp.ecoenchants.proxy.v1_21_3.ModernEnchantmentRegisterer
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:199) ~[purpur-api-1.21.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:166) ~[purpur-api-1.21.3-R0.1-SNAPSHOT.jar:?]
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:528) ~[?:?]
        at eco-6.74.5-all.jar/com.willfp.eco.internal.proxy.EcoProxyFactory.getProxy(EcoProxyFactory.kt:29) ~[eco-6.74.5-all.jar:?]
        at eco-6.74.5-all.jar/com.willfp.eco.core.EcoPlugin.getProxy(EcoPlugin.java:967) ~[eco-6.74.5-all.jar:?]
        at EcoEnchants_v12.3.0.jar/com.willfp.ecoenchants.EcoEnchantsPlugin.<init>(EcoEnchantsPlugin.kt:57) ~[EcoEnchants_v12.3.0.jar:?]
        at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62) ~[?:?]
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:501) ~[?:?]
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:485) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:100) ~[purpur-api-1.21.3-R0.1-SNAPSHOT.jar:?]
        ... 10 more
```
help.
(Eco and ProtoocolLib:installed)

**Comment by Nicolol1234** [comment]
i have the same problem :(

**Comment by Ericlyclyclyc** [comment]
Now,I even can't visit gitub.com...
lyc

________________________________
发件人: Nicolol1234 ***@***.***>
发送时间: 2024年12月29日 20:12
收件人: Auxilor/EcoEnchants ***@***.***>
抄送: Ericlyclyclyc ***@***.***>; Author ***@***.***>
主题: Re: [Auxilor/EcoEnchants] Why proxies don't work??? (Issue #405)


i have the same problem :(

―

**Comment by Ericlyclyclyc** [comment]
I'll try Paper instead.

**Comment by Ericlyclyclyc** [comment]
Now,we know that it WILL NOT work with Velocity on Paper,too...
`[00:45:59 ERROR]: [EcoEnchants] Fatal error with proxies! This plugin can't load.
[00:45:59 ERROR]: [ModernPluginLoadingStrategy] Could not load plugin 'EcoEnchants_v12.3.0.jar' in folder 'plugins\.paper-remapped'
org.bukkit.plugin.InvalidPluginException: Exception initializing main class `com.willfp.ecoenchants.EcoEnchantsPlugin'
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:106) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProvider.createInstance(SpigotPluginProvider.java:125) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
        at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProvider.createInstance(SpigotPluginProvider.java:35) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
        at io.papermc.paper.plugin.entrypoint.strategy.modern.ModernPluginLoadingStrategy.loadProviders(ModernPluginLoadingStrategy.java:116) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
        at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:38) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
        at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:40) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
        at org.bukkit.craftbukkit.CraftServer.loadPlugins(CraftServer.java:547) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:292) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1214) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329) ~[paper-1.21.1.jar:1.21.1-132-b48403b]
        at java.base/java.lang.Thread.run(Thread.java:1575) ~[?:?]
Caused by: java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:74) ~[?:?]
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:501) ~[?:?]
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:485) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:98) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        ... 10 more
Caused by: com.willfp.eco.core.proxy.exceptions.ProxyError: Could not initialize proxy. Are you running a supported server version?
        at eco-6.74.5-all.jar/com.willfp.eco.internal.proxy.EcoProxyFactory.proxyErrorFrom(EcoProxyFactory.kt:52) ~[eco-6.74.5-all.jar:?]
        at eco-6.74.5-all.jar/com.willfp.eco.internal.proxy.EcoProxyFactory.getProxy(EcoProxyFactory.kt:37) ~[eco-6.74.5-all.jar:?]
        at eco-6.74.5-all.jar/com.willfp.eco.core.EcoPlugin.getProxy(EcoPlugin.java:967) ~[eco-6.74.5-all.jar:?]
        at EcoEnchants_v12.3.0.jar/com.willfp.ecoenchants.EcoEnchantsPlugin.<init>(EcoEnchantsPlugin.kt:57) ~[EcoEnchants_v12.3.0.jar:?]
        at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62) ~[?:?]
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:501) ~[?:?]
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:485) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:98) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        ... 10 more
Caused by: java.lang.ClassNotFoundException: com.willfp.ecoenchants.proxy.v1_21.ModernEnchantmentRegisterer
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:197) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:164) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:528) ~[?:?]
        at eco-6.74.5-all.jar/com.willfp.eco.internal.proxy.EcoProxyFactory.getProxy(EcoProxyFactory.kt:29) ~[eco-6.74.5-all.jar:?]
        at eco-6.74.5-all.jar/com.willfp.eco.core.EcoPlugin.getProxy(EcoPlugin.java:967) ~[eco-6.74.5-all.jar:?]
        at EcoEnchants_v12.3.0.jar/com.willfp.ecoenchants.EcoEnchantsPlugin.<init>(EcoEnchantsPlugin.kt:57) ~[EcoEnchants_v12.3.0.jar:?]
        at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62) ~[?:?]
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:501) ~[?:?]
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:485) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:98) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        ... 10 more`
`[00:49:10 INFO]: This server is running Paper version 1.21.1-132-ver/1.21.1@b48403b (2024-11-21T10:14:27Z) (Implementing API version 1.21.1-R0.1-SNAPSHOT)` - Paper version
Velocity's version is the same.

**Comment by Ericlyclyclyc** [comment]
then,i found this...
`Caused by: com.willfp.eco.core.proxy.exceptions.ProxyError: Could not initialize proxy. Are you running a supported server version?`
What can i say to THIS???

**Comment by Nicolol1234** [comment]
![image](https://github.com/user-attachments/assets/21535e15-116b-4f64-969c-ce46582428c6)

**Comment by Nicolol1234** [comment]
marked as compatible as i show the image tho, weird issue

**Comment by Nicolol1234** [comment]
> The version is not correct...[12.3.0] but it should support 1.21.1...

It's the plugin version, not the Minecraft version

**Comment by Ericlyclyclyc** [comment]
so i think v12.3.0(plugin) should support 1.21.1(minecraft)

**Comment by devbaraus** [comment]
I'm having this problem on version paper 1.21.4 and ecoenchants 12.19.4

**Comment by Ericlyclyclyc** [comment]
WAIT...
What's this???
`Caused by: java.lang.ClassNotFoundException: com.willfp.ecoenchants.proxy.v1_21.ModernEnchantmentRegisterer`
Is this the reason?
