### ISSUE TITLE
Error with eco & EcoEnchant

### ISSUE THREAD

**Issue by iZeroneX** [Auxilor/EcoEnchants#61]
I'm suffering from this issue for a month. 
Still do not know how to solve.
`
[23:33:37 INFO]: [eco] Loaded eco
[23:33:38 WARN]: java.lang.reflect.InvocationTargetException
[23:33:38 WARN]:        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[23:33:38 WARN]:        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
[23:33:38 WARN]:        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[23:33:38 WARN]:        at java.base/java.lang.reflect.Method.invoke(Method.java:567)
[23:33:38 WARN]:        at eco-6.7.3-all.jar//com.willfp.eco.internal.config.updating.EcoConfigHandler.callUpdate(EcoConfigHandler.kt:33)
[23:33:38 WARN]:        at eco-6.7.3-all.jar//com.willfp.eco.core.EcoPlugin.reload(EcoPlugin.java:478)
[23:33:38 WARN]:        at eco-6.7.3-all.jar//com.willfp.eco.core.EcoPlugin.afterLoad(EcoPlugin.java:467)
[23:33:38 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101)
[23:33:38 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483)
[23:33:38 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1221)
[23:33:38 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319)
[23:33:38 WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)
[23:33:38 WARN]: Caused by: java.lang.NullPointerException: Cannot invoke "com.willfp.ecoenchants.enchantments.support.vanilla.VanillaEnchantmentMetadata.maxLevel()" because "this.metadata" is null
[23:33:38 WARN]:        at EcoEnchants v8.10.11.jar//com.willfp.ecoenchants.proxy.v1_17_R1.enchants.EcoCraftEnchantment.getMaxLevel(EcoCraftEnchantment.java:21)
[23:33:38 WARN]:        at EcoEnchants v8.10.11.jar//com.willfp.ecoenchants.display.EnchantmentCache.updateEnchantment(EnchantmentCache.java:159)
[23:33:38 WARN]:        at java.base/java.util.Arrays$ArrayList.forEach(Arrays.java:4203)
[23:33:38 WARN]:        at EcoEnchants v8.10.11.jar//com.willfp.ecoenchants.display.EnchantmentCache.update(EnchantmentCache.java:79)
[23:33:38 WARN]:        ... 12 more
[23:33:38 WARN]: [EcoEnchants] Task #25 for EcoEnchants v8.10.11 generated an exception
com.willfp.eco.internal.config.updating.exceptions.InvalidUpdateMethodException: Update method generated an exception
        at com.willfp.eco.internal.config.updating.EcoConfigHandler.callUpdate(EcoConfigHandler.kt:39) ~[eco-6.7.3-all.jar:?]
        at com.willfp.eco.core.EcoPlugin.reload(EcoPlugin.java:478) ~[eco-6.7.3-all.jar:?]
        at com.willfp.eco.core.EcoPlugin.afterLoad(EcoPlugin.java:467) ~[eco-6.7.3-all.jar:?]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.17.1.jar:git-Airplane-76]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[patched_1.17.1.jar:git-Airplane-76]
        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1221) ~[patched_1.17.1.jar:git-Airplane-76]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Airplane-76]
        at java.lang.Thread.run(Thread.java:831) [?:?]
`

**Comment by lokka30** [comment]
> I'm suffering from this issue for a month. Still do not know how to solve. `[23:33:37 INFO]: [eco] Loaded eco [23:33:38 WARN]: java.lang.reflect.InvocationTargetException [23:33:38 WARN]: at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) [23:33:38 WARN]: at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) [23:33:38 WARN]: at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) [23:33:38 WARN]: at java.base/java.lang.reflect.Method.invoke(Method.java:567) [23:33:38 WARN]: at eco-6.7.3-all.jar//com.willfp.eco.internal.config.updating.EcoConfigHandler.callUpdate(EcoConfigHandler.kt:33) [23:33:38 WARN]: at eco-6.7.3-all.jar//com.willfp.eco.core.EcoPlugin.reload(EcoPlugin.java:478) [23:33:38 WARN]: at eco-6.7.3-all.jar//com.willfp.eco.core.EcoPlugin.afterLoad(EcoPlugin.java:467) [23:33:38 WARN]: at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) [23:33:38 WARN]: at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) [23:33:38 WARN]: at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1221) [23:33:38 WARN]: at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) [23:33:38 WARN]: at java.base/java.lang.Thread.run(Thread.java:831) [23:33:38 WARN]: Caused by: java.lang.NullPointerException: Cannot invoke "com.willfp.ecoenchants.enchantments.support.vanilla.VanillaEnchantmentMetadata.maxLevel()" because "this.metadata" is null [23:33:38 WARN]: at EcoEnchants v8.10.11.jar//com.willfp.ecoenchants.proxy.v1_17_R1.enchants.EcoCraftEnchantment.getMaxLevel(EcoCraftEnchantment.java:21) [23:33:38 WARN]: at EcoEnchants v8.10.11.jar//com.willfp.ecoenchants.display.EnchantmentCache.updateEnchantment(EnchantmentCache.java:159) [23:33:38 WARN]: at java.base/java.util.Arrays$ArrayList.forEach(Arrays.java:4203) [23:33:38 WARN]: at EcoEnchants v8.10.11.jar//com.willfp.ecoenchants.display.EnchantmentCache.update(EnchantmentCache.java:79) [23:33:38 WARN]: ... 12 more [23:33:38 WARN]: [EcoEnchants] Task #25 for EcoEnchants v8.10.11 generated an exception com.willfp.eco.internal.config.updating.exceptions.InvalidUpdateMethodException: Update method generated an exception at com.willfp.eco.internal.config.updating.EcoConfigHandler.callUpdate(EcoConfigHandler.kt:39) ~[eco-6.7.3-all.jar:?] at com.willfp.eco.core.EcoPlugin.reload(EcoPlugin.java:478) ~[eco-6.7.3-all.jar:?] at com.willfp.eco.core.EcoPlugin.afterLoad(EcoPlugin.java:467) ~[eco-6.7.3-all.jar:?] at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.17.1.jar:git-Airplane-76] at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[patched_1.17.1.jar:git-Airplane-76] at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1221) ~[patched_1.17.1.jar:git-Airplane-76] at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Airplane-76] at java.lang.Thread.run(Thread.java:831) [?:?]`

Please check if your Java is up-to-date. I receive a similar error when running the incorrect Java version for my Forge modpack.
