### ISSUE TITLE
EcoEnchant & Oraxen

### ISSUE THREAD

**Issue by LeAnhTuan0810** [Auxilor/EcoEnchants#62]
when I install both plugins it gives error
```
[20:40:01 WARN]: [eco] Task #10 for eco v6.7.3 generated an exception
java.lang.NullPointerException: getIdByItem(item) must not be null
        at com.willfp.eco.spigot.integrations.customitems.CustomItemsOraxen.registerAllItems(CustomItemsOraxen.kt:15) ~[?:?]
        at com.willfp.eco.core.integrations.customitems.CustomItemsManager.registerAllItems(CustomItemsManager.java:35) ~[?:?]
        at com.willfp.eco.spigot.EcoSpigotPlugin.handleAfterLoad(EcoSpigotPlugin.kt:91) ~[?:?]
        at com.willfp.eco.core.EcoPlugin.afterLoad(EcoPlugin.java:465) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.16.5.jar:git-Paper-788]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:485) ~[patched_1.16.5.jar:git-Paper-788]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1078) ~[patched_1.16.5.jar:git-Paper-788]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Paper-788]
        at java.lang.Thread.run(Thread.java:831) [?:?]
[20:40:01 INFO]: [EcoEnchants] Loaded EcoEnchants

```

**Comment by Wesley51** [comment]
update
