### ISSUE TITLE
[eco] Unhandled exception occured in onPacketSending(PacketEvent) for eco

### ISSUE THREAD

**Issue by a-verk** [Auxilor/EcoEnchants#88]
[08:22:26 ERROR]: [eco] Unhandled exception occured in onPacketSending(PacketEvent) for eco
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BOOLEAN but was STRING at path $.italic
        at com.google.gson.Gson.fromJson(Gson.java:899) ~[patched_1.17.1.jar:git-Purpur-1402]
        at com.google.gson.Gson.fromJson(Gson.java:952) ~[patched_1.17.1.jar:git-Purpur-1402]
        at com.google.gson.Gson.fromJson(Gson.java:925) ~[patched_1.17.1.jar:git-Purpur-1402]
        at net.kyori.adventure.text.serializer.gson.ComponentSerializerImpl.read(ComponentSerializerImpl.java:214) ~[patched_1.17.1.jar:git-Purpur-1402]
        at net.kyori.adventure.text.serializer.gson.ComponentSerializerImpl.read(ComponentSerializerImpl.java:56) ~[patched_1.17.1.jar:git-Purpur-1402]
        at com.google.gson.TypeAdapter$1.read(TypeAdapter.java:199) ~[patched_1.17.1.jar:git-Purpur-1402]
        at com.google.gson.Gson.fromJson(Gson.java:887) ~[patched_1.17.1.jar:git-Purpur-1402]
        at com.google.gson.Gson.fromJson(Gson.java:852) ~[patched_1.17.1.jar:git-Purpur-1402]
        at com.google.gson.Gson.fromJson(Gson.java:801) ~[patched_1.17.1.jar:git-Purpur-1402]
        at com.google.gson.Gson.fromJson(Gson.java:773) ~[patched_1.17.1.jar:git-Purpur-1402]
        at net.kyori.adventure.text.serializer.gson.GsonComponentSerializerImpl.deserialize(GsonComponentSerializerImpl.java:84) ~[patched_1.17.1.jar:git-Purpur-1402]
        at net.kyori.adventure.text.serializer.gson.GsonComponentSerializerImpl.deserialize(GsonComponentSerializerImpl.java:37) ~[patched_1.17.1.jar:git-Purpur-1402]
        at com.willfp.eco.util.StringUtils.jsonToLegacy(StringUtils.java:435) ~[eco-6.10.0-all.jar:?]
        at com.willfp.eco.proxy.v1_17_R1.fast.NMSFastItemStack.getLore(NMSFastItemStack.kt:96) ~[eco-6.10.0-all.jar:?]
        at com.willfp.eco.internal.display.EcoDisplayHandler.revert(EcoDisplayHandler.kt:71) ~[eco-6.10.0-all.jar:?]
        at com.willfp.eco.core.display.Display.revert(Display.java:76) ~[eco-6.10.0-all.jar:?]
        at com.willfp.eco.internal.display.EcoDisplayHandler.display(EcoDisplayHandler.kt:50) ~[eco-6.10.0-all.jar:?]
        at com.willfp.eco.core.display.Display.display(Display.java:44) ~[eco-6.10.0-all.jar:?]
        at com.willfp.eco.spigot.display.PacketSetSlot.onSend$lambda-0(PacketSetSlot.kt:19) ~[eco-6.10.0-all.jar:?]
        at com.comphenix.protocol.reflect.StructureModifier.modify(StructureModifier.java:424) ~[ProtocolLib (7).jar:?]
        at com.willfp.eco.spigot.display.PacketSetSlot.onSend(PacketSetSlot.kt:18) ~[eco-6.10.0-all.jar:?]
        at com.willfp.eco.core.AbstractPacketAdapter.onPacketSending(AbstractPacketAdapter.java:121) ~[eco-6.10.0-all.jar:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) ~[ProtocolLib (7).jar:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) ~[ProtocolLib (7).jar:?]
        at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:535) ~[ProtocolLib (7).jar:?]
        at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:516) ~[ProtocolLib (7).jar:?]
        at com.comphenix.protocol.injector.netty.ProtocolInjector.packetQueued(ProtocolInjector.java:346) ~[ProtocolLib (7).jar:?]
        at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketSending(ProtocolInjector.java:308) ~[ProtocolLib (7).jar:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:433) ~[ProtocolLib (7).jar:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector.access$800(ChannelInjector.java:70) ~[ProtocolLib (7).jar:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector$3.handleScheduled(ChannelInjector.java:373) ~[ProtocolLib (7).jar:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector$3.onMessageScheduled(ChannelInjector.java:343) ~[ProtocolLib (7).jar:?]
        at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:127) ~[ProtocolLib (7).jar:?]
        at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:95) ~[ProtocolLib (7).jar:?]
        at net.minecraft.network.Connection.writePacket(Connection.java:423) ~[app:?]
        at net.minecraft.network.Connection.send(Connection.java:370) ~[app:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.send(ServerGamePacketListenerImpl.java:2074) ~[app:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.send(ServerGamePacketListenerImpl.java:2060) ~[app:?]
        at org.bukkit.craftbukkit.v1_17_R1.inventory.CraftInventoryPlayer.setItem(CraftInventoryPlayer.java:113) ~[patched_1.17.1.jar:git-Purpur-1402]
        at org.bukkit.craftbukkit.v1_17_R1.inventory.CraftInventory.setContents(CraftInventory.java:92) ~[patched_1.17.1.jar:git-Purpur-1402]
        at com.Zrips.CMI.Modules.InvRegEditor.RegChestManager$2.run(RegChestManager.java:191) ~[CMI9.0.2.5.jar:?]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.17.1.jar:git-Purpur-1402]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[patched_1.17.1.jar:git-Purpur-1402]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1583) ~[patched_1.17.1.jar:git-Purpur-1402]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:518) ~[patched_1.17.1.jar:git-Purpur-1402]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1499) ~[patched_1.17.1.jar:git-Purpur-1402]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1292) ~[patched_1.17.1.jar:git-Purpur-1402]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:322) ~[patched_1.17.1.jar:git-Purpur-1402]
        at java.lang.Thread.run(Thread.java:831) ~[?:?]
Caused by: java.lang.IllegalStateException: Expected BOOLEAN but was STRING at path $.italic
        at com.google.gson.internal.bind.JsonTreeReader.expect(JsonTreeReader.java:162) ~[patched_1.17.1.jar:git-Purpur-1402]
        at com.google.gson.internal.bind.JsonTreeReader.nextBoolean(JsonTreeReader.java:190) ~[patched_1.17.1.jar:git-Purpur-1402]
        at net.kyori.adventure.text.serializer.gson.StyleSerializer.read(StyleSerializer.java:114) ~[patched_1.17.1.jar:git-Purpur-1402]
        at net.kyori.adventure.text.serializer.gson.StyleSerializer.read(StyleSerializer.java:49) ~[patched_1.17.1.jar:git-Purpur-1402]
        at com.google.gson.TypeAdapter$1.read(TypeAdapter.java:199) ~[patched_1.17.1.jar:git-Purpur-1402]
        at com.google.gson.Gson.fromJson(Gson.java:887) ~[patched_1.17.1.jar:git-Purpur-1402]
        ... 48 more
[08:22:26 ERROR]: Parameters: 
  net.minecraft.network.protocol.game.PacketPlayOutSetSlot@4265aec2[
    c=0
    d=441
    e=32
    f=1 red_wool
  ]

**Comment by a-verk** [comment]
After updating to the latest version of Eco, errors started pouring in and every other time players lose their enchantments from your plugin


Latest Purpur Server Core

Server version 1.17.1
